export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };

  export const registerConstants = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
  
    SENDOTP_REQUEST:"SENDOTP_REQUEST",
    SENDOTP_SUCCESS:"SENDOTP_SUCCESS",
    SENDOTP_FAILURE:"SENDOTP_FAILURE",
  
    VERIFYOTP_REQUEST:"VERIFYOTP_REQUEST",
    VERIFYOTP_SUCCESS:"VERIFYOTP_SUCCESS",
    VERIFYOTP_FAILURE:"VERIFYOTP_FAILURE"
  };
  
export const AdminConstants = {
  GETBYIDUSER_ADMIN_REQUEST: "GETBYIDUSER_ADMIN_REQUEST",
  GETBYIDUSER_ADMIN_FAILURE: "GETBYIDUSER_ADMIN_FAILURE",
  GETBYIDUSER_ADMIN_SUCCESS: "GETBYIDUSER_ADMIN_SUCCESS",

  UPDATE_ADMIN_REQUEST: "UPDATE_ADMIN_REQUEST",
  UPDATE_ADMIN_SUCCESS: "UPDATE_ADMIN_SUCCESS",
  UPDATE_ADMIN_FAILURE: "UPDATE_ADMIN_FAILURE",
  
  GET_ADMIN_REQUEST: "GET_ADMIN_REQUEST",
  GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
  GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE"
};

export const CoursConstants = {

  GETBYIDUSER_COURS_REQUEST: "GETBYIDUSER_COURS_REQUEST",
  GETBYIDUSER_COURS_FAILURE: "GETBYIDUSER_COURS_FAILURE",
  GETBYIDUSER_COURS_SUCCESS: "GETBYIDUSER_COURS_SUCCESS",

  GET_COURS_REQUEST: "GET_COURS_REQUEST",
  GET_COURS_SUCCESS: "GET_COURS_SUCCESS",
  GET_COURS_FAILURE: "GET_COURS_FAILURE",

  ADD_COURS_REQUEST: "ADD_COURS_REQUEST",
  ADD_COURS_SUCCESS: "ADD_COURS_SUCCESS",
  ADD_COURS_FAILURE: "ADD_COURS_FAILURE",

  UPDATE_COURS_REQUEST: "UPDATE_COURS_REQUEST",
  UPDATE_COURS_SUCCESS: "UPDATE_COURS_SUCCESS",
  UPDATE_COURS_FAILURE: "UPDATE_COURS_FAILURE",

  DELETE_COURS_REQUEST: "DELETE_COURS_REQUEST",
  DELETE_COURS_SUCCESS: "DELETE_COURS_SUCCESS",
  DELETE_COURS_FAILURE: "DELETE_COURS_FAILURE",

  UPDATE_COURS_REQUEST: "UPDATE_COURS_REQUEST",
  UPDATE_COURS_SUCCESS: "UPDATE_COURS_SUCCESS",
  UPDATE_COURS_FAILURE: "UPDATE_COURS_FAILURE",

};